import '../globals.css';
import Link from "next/link";
export const metadata = {
    title: "Admin Panel",
    description: "Generated by Next.js",
  };

export default function adminLayout({children}){
    return(
        <html lang="en">
        <body>
          <div className="min-h-screen flex">
            <div className="w-1/3 bg-teal-200">
             <Link href={'/Admin'}><h1>Dashboard</h1></Link> 
             <Link href={'/Admin/products'}><h1>Products</h1></Link> 
             <Link href={'/Admin/categories'}><h1>Categories</h1></Link> 
            </div>
            <div className="w-2/3 bg-fuchsia-300">{children}</div>
          </div>
        </body>
      </html>
    )
}